language: c
dist: trusty
sudo: required

notifications:
  email: false
git:
  submodules: true

matrix:
  include:
  - os: osx
    compiler: clang
    install:
      - git submodule update --init --recursive
      - brew install pkg-config
    script:
      - mkdir faust/build/personal && cd faust/build/personal
      - cmake .. -DINCLUDE_STATIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off
      - make
