os: Visual Studio 2015

environment:
  matrix:
  #- platform: Win32
  #  compiler: "Visual Studio 14 2015"
  #  configuration: Debug
  #  llvmversion: 6.0.0
  #  llvmplateform: x86
  - platform: x64
    compiler: "Visual Studio 14 2015 Win64"
    configuration: Debug
    llvmversion: 6.0.0
    llvmplateform: x64

install:
  - git submodule update --init --recursive
  - curl -L https://github.com/pierreguillot/llvm-win/releases/download/v%llvmversion%/llvm-windows-%llvmplateform%-mtd.zip -o llvm.zip
  - 7z x llvm.zip
build_script:
  - mkdir build%llvmplateform% && cd build%llvmplateform%
  - cmake .. -G "%compiler%" -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./llvm-windows-%llvmplateform%-mtd/lib/cmake/llvm
  - msbuild faust~.sln /nologo /p:config=%configuration% /p:plateform=%platform%
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - del /F /Q llvm.zip
  - del /F /S /Q /A external\*.pdb
  - del /F /S /Q /A external\*.ilk
  - del /F /S /Q /A external\*.lib
  - copy src\faust_tilde.c external\faust_tilde.c
  - copy README.md external\README.md
  - copy LICENSE external\LICENSE.txt
  - rename external faust_tilde
  - 7z a faust_tilde-win-%llvmplateform%.zip faust_tilde

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: 0SV8u3c06daN/cno+27kzzIvWbsRoOOG61OOCNEtiYbsoY8FNe4TgZh+s/7zcMiL
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
